name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          # update pip
          python -m pip install --upgrade pip
          # install flake8 and plugins
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # installing dependencies
          pip install -r backend/requirements.txt

      - name: Test with flake8
        run: |
          # Launch project check with flake8
          python -m flake8